let arrContent = {
  verben: {
    können: 'могти',
    müssen: 'повинний',
    dürfen: 'мати дозвіл',
    sollen: 'треба, слід',
    wollen: 'хотіти',
    machen: 'робити',
    gehen: 'йти',
    kommen: 'приходити',
    sehen: 'бачити',
    hören: 'чути',
    sprechen: 'говорити',
    lesen: 'читати',
    schreiben: 'писати',
    essen: 'їсти',
    trinken: 'пити',
    schlafen: 'спати',
    fahren: 'їхати',
    laufen: 'бігти, ходити',
    lernen: 'вчитися',
    verstehen: 'розуміти',
    arbeiten: 'працювати',
    brauchen: 'потрібно',
    haben: 'мати',
    sein: 'бути',
    werden: 'ставати',
    bleiben: 'залишатися',
    beginnen: 'починати',
    enden: 'закінчувати',
    vergessen: 'забувати',
    finden: 'знаходити',
    suchen: 'шукати',
    gewinnen: 'вигравати',
    verlieren: 'програвати',
    fragen: 'питати',
    antworten: 'відповідати',
    kaufen: 'купувати',
    verkaufen: 'продавати',
    lieben: 'любити',
    hassen: 'ненавидіти',
    zeigen: 'показувати',
    erklären: 'пояснювати',
    spielen: 'грати',
    treffen: 'зустрічати',
    einladen: 'запрошувати',
    besuchen: 'відвідувати',
    warten: 'чекати',
    öffnen: 'відкривати',
    schließen: 'закривати',
    stehen: 'стояти',
    sitzen: 'сидіти',
    liegen: 'лежати',
    fühlen: 'відчувати',
    denken: 'думати',
    glauben: 'вірити, думати',
    erinnern: 'пам’ятати',
    vergleichen: 'порівнювати',
    helfen: 'допомагати',
    anfangen: 'починати',
    beenden: 'завершувати',
    schicken: 'надсилати',
    bekommen: 'отримувати',
    wissen: 'знати',
    kennen: 'знати (когось, щось)',
    tragen: 'носити',
    waschen: 'мити',
    putzen: 'чистити',
    kochen: 'готувати',
    backen: 'пекти',
    rennen: 'бігти',
    springen: 'стрибати',
    schwimmen: 'плавати',
    tauchen: 'пірнати',
    fliegen: 'літати',
    reisen: 'подорожувати',
    besichtigen: 'оглядати',
    fotografieren: 'фотографувати',
    tanzen: 'танцювати',
    singen: 'співати',
    zeichnen: 'малювати',
    malen: 'фарбувати, малювати',
    üben: 'практикуватися',
    probieren: 'пробувати',
    liefern: 'доставляти',
    entscheiden: 'вирішувати',
    planen: 'планувати',
    organisieren: 'організовувати',
    erleben: 'досвідчувати',
    entdecken: 'відкривати',
    erforschen: 'досліджувати',
    unterstützen: 'підтримувати',
    verbessern: 'покращувати',
    trainieren: 'тренуватися',
    erholen: 'відпочивати',
    genießen: 'насолоджуватися',
    feiern: 'святкувати',
    lächeln: 'посміхатися',
    weinen: 'плакати',
    schreien: 'кричати'
  },
  adjectives: {
    groß: 'великий',
    klein: 'малий',
    lang: 'довгий',
    kurz: 'короткий',
    hoch: 'високий',
    niedrig: 'низький',
    alt: 'старий',
    jung: 'молодий',
    neu: 'новий',
    schön: 'гарний',
    hässlich: 'потворний',
    gut: 'добрий',
    schlecht: 'поганий',
    stark: 'сильний',
    schwach: 'слабкий',
    warm: 'теплий',
    kalt: 'холодний',
    heiß: 'гарячий',
    trocken: 'сухий',
    nass: 'мокрий',
    schnell: 'швидкий',
    langsam: 'повільний',
    leicht: 'легкий',
    schwer: 'важкий',
    teuer: 'дорогий',
    billig: 'дешевий',
    sauber: 'чистий',
    schmutzig: 'брудний',
    freundlich: 'дружній',
    unfreundlich: 'недружній',
    glücklich: 'щасливий',
    traurig: 'сумний',
    klug: 'розумний',
    dumm: 'дурний',
    lustig: 'смішний',
    ernst: 'серйозний',
    ruhig: 'спокійний',
    laut: 'голосний',
    interessant: 'цікавий',
    langweilig: 'нудний',
    gesund: 'здоровий',
    krank: 'хворий',
    reich: 'багатий',
    arm: 'бідний',
    sauber: 'чистий',
    scharf: 'гострий',
    weich: 'м’який',
    hart: 'твердий',
    schön: 'гарний',
    hässlich: 'потворний',
    offen: 'відкритий',
    geschlossen: 'закритий',
    bequem: 'зручний',
    unbequem: 'незручний',
    freundlich: 'дружній',
    feindlich: 'ворожий',
    sicher: 'безпечний',
    gefährlich: 'небезпечний',
    hell: 'світлий',
    dunkel: 'темний',
    warmherzig: 'добросердний',
    kaltblütig: 'бездушний',
    sauber: 'чистий',
    schmutzig: 'брудний',
    stolz: 'гордий',
    bescheiden: 'скромний',
    mutig: 'сміливий',
    ängstlich: 'боязкий',
    stark: 'сильний',
    schwach: 'слабкий',
    treu: 'вірний',
    untreu: 'невірний',
    freundlich: 'дружній',
    unfreundlich: 'недружній',
    elegant: 'елегантний',
    hässlich: 'потворний',
    warm: 'теплий',
    kalt: 'холодний',
    süß: 'солодкий',
    sauer: 'кислий',
    bitter: 'гіркий',
    salzig: 'солоний',
    dick: 'товстий',
    dünn: 'тонкий',
    sauber: 'чистий',
    schmutzig: 'брудний',
    scharf: 'гострий',
    stumpf: 'тупий',
    intelligent: 'розумний',
    dumm: 'дурний',
    lustig: 'веселий',
    traurig: 'сумний',
    glücklich: 'щасливий',
    unglücklich: 'нещасний',
    neu: 'новий',
    alt: 'старий',
    modern: 'сучасний',
    traditionell: 'традиційний',
    interessant: 'цікавий',
    langweilig: 'нудний',
    sauber: 'чистий',
    schmutzig: 'брудний',
    leicht: 'легкий',
    schwer: 'важкий',
    stark: 'сильний',
    schwach: 'слабкий',
    warm: 'теплий',
    kalt: 'холодний',
    nah: 'близький',
    fern: 'далекий',
    schön: 'гарний',
    hässlich: 'потворний',
    jung: 'молодий',
    alt: 'старий',
    offen: 'відкритий',
    verschlossen: 'замкнений'
  },
  nomen: {
    'der haus': 'будинок',
  'das auto': 'авто',
  'der stuhl': 'стілець',
  'der tisch': 'стіл',
  'das fenster': 'вікно',
  'die tür': 'двері',
  'das bett': 'ліжко',
  'die schule': 'школа',
  'der lehrer': 'вчитель',
  'die schülerin': 'учениця',
  'der schüler': 'учень',
  'die bücher': 'книги',
  'die stadt': 'місто',
  'das dorf': 'село',
  'die straße': 'вулиця',
  'der park': 'парк',
  'die brücke': 'міст',
  'der fluss': 'річка',
  'der see': 'озеро',
  'der berg': 'гора',
  'der wald': 'ліс',
  'die blume': 'квітка',
  'der baum': 'дерево',
  'der vogel': 'птах',
  'der hund': 'собака',
  'die katze': 'кішка',
  'der fisch': 'риба',
  'das essen': 'їжа',
  'das getränk': 'напій',
  'das brot': 'хліб',
  'die milch': 'молоко',
  'der kaffee': 'кава',
  'der tee': 'чай',
  'die suppe': 'суп',
  'der kuchen': 'тістечко',
  'die schokolade': 'шоколад',
  'der freund': 'друг',
  'die freundin': 'подруга',
  'die familie': 'сім’я',
  'die mutter': 'мати',
  'der vater': 'батько',
  'der bruder': 'брат',
  'die schwester': 'сестра',
  'die oma': 'бабуся',
  'der opa': 'дідусь',
  'das baby': 'дитина',
  'das kind': 'дитина',
  'der mann': 'чоловік',
  'die frau': 'жінка',
  'der junge': 'хлопчик',
  'das mädchen': 'дівчинка',
  'die arbeit': 'робота',
  'der chef': 'шеф',
  'der kollege': 'колега',
  'der termin': 'зустріч',
  'die stunde': 'година',
  'die minute': 'хвилина',
  'die sekunde': 'секунда',
  'der tag': 'день',
  'die woche': 'тиждень',
  'der monat': 'місяць',
  'das jahr': 'рік',
  'die saison': 'сезон',
  'der frühling': 'весна',
  'der sommer': 'літо',
  'der herbst': 'осінь',
  'der winter': 'зима',
  'das wetter': 'погода',
  'der regen': 'дощ',
  'der schnee': 'сніг',
  'der wind': 'вітер',
  'die sonne': 'сонце',
  'der mond': 'місяць',
  'der stern': 'зірка',
  'der himmel': 'небо',
  'das meer': 'море',
  'der strand': 'пляж',
  'der sand': 'пісок',
  'der stein': 'камінь',
  'das blatt': 'листок',
  'das gras': 'трава',
  'das tier': 'тварина',
  'der zoo': 'зоопарк',
  'das krankenhaus': 'лікарня',
  'der arzt': 'лікар',
  'die apotheke': 'аптека',
  'der supermarkt': 'супермаркет',
  'der laden': 'магазин',
  'der markt': 'ринок',
  'der bahnhof': 'вокзал',
  'der zug': 'поїзд',
  'der bus': 'автобус',
  'das flugzeug': 'літак',
  'das fahrrad': 'велосипед',
  'die straßenbahn': 'трамвай',
  'das taxi': 'таксі',
  'der flughafen': 'аеропорт',
  'der koffer': 'чемодан',
  'die tasche': 'сумка',
  'das telefon': 'телефон',
  'der computer': 'комп’ютер',
  'das handy': 'мобільний телефон',
  'das buch': 'книга',
  'die zeitung': 'газета',
  'das foto': 'фото',
  'der film': 'фільм',
  'die musik': 'музика',
  'das spiel': 'гра',
  'das hobby': 'хобі',
  'der sport': 'спорт',
  'das team': 'команда',
  'die liga': 'ліга',
  'der spieler': 'гравець',
  'der trainer': 'тренер'
  },
  ausgewählt: {

  },
}
export default arrContent