let arrContent = {
  verben: {
    können: 'могти',
    müssen: 'повинний',
    dürfen: 'мати дозвіл',
    sollen: 'треба, слід',
    wollen: 'хотіти',
    machen: 'робити',
    gehen: 'йти',
    kommen: 'приходити',
    sehen: 'бачити',
    hören: 'чути',
    sprechen: 'говорити',
    lesen: 'читати',
    schreiben: 'писати',
    essen: 'їсти',
    trinken: 'пити',
    schlafen: 'спати',
    fahren: 'їхати',
    laufen: 'бігти, ходити',
    lernen: 'вчитися',
    verstehen: 'розуміти',
    arbeiten: 'працювати',
    brauchen: 'потрібно',
    haben: 'мати',
    sein: 'бути',
    werden: 'ставати',
    bleiben: 'залишатися',
    beginnen: 'починати',
    enden: 'закінчувати',
    vergessen: 'забувати',
    finden: 'знаходити',
    suchen: 'шукати',
    gewinnen: 'вигравати',
    verlieren: 'програвати',
    fragen: 'питати',
    antworten: 'відповідати',
    kaufen: 'купувати',
    verkaufen: 'продавати',
    lieben: 'любити',
    hassen: 'ненавидіти',
    zeigen: 'показувати',
    erklären: 'пояснювати',
    spielen: 'грати',
    treffen: 'зустрічати',
    einladen: 'запрошувати',
    besuchen: 'відвідувати',
    warten: 'чекати',
    öffnen: 'відкривати',
    schließen: 'закривати',
    stehen: 'стояти',
    sitzen: 'сидіти',
    liegen: 'лежати',
    fühlen: 'відчувати',
    denken: 'думати',
    glauben: 'вірити, думати',
    erinnern: 'пам’ятати',
    vergleichen: 'порівнювати',
    helfen: 'допомагати',
    anfangen: 'починати',
    beenden: 'завершувати',
    schicken: 'надсилати',
    bekommen: 'отримувати',
    wissen: 'знати',
    kennen: 'знати (когось, щось)',
    tragen: 'носити',
    waschen: 'мити',
    putzen: 'чистити',
    kochen: 'готувати',
    backen: 'пекти',
    rennen: 'бігти',
    springen: 'стрибати',
    schwimmen: 'плавати',
    tauchen: 'пірнати',
    fliegen: 'літати',
    reisen: 'подорожувати',
    besichtigen: 'оглядати',
    fotografieren: 'фотографувати',
    tanzen: 'танцювати',
    singen: 'співати',
    zeichnen: 'малювати',
    malen: 'фарбувати, малювати',
    üben: 'практикуватися',
    probieren: 'пробувати',
    liefern: 'доставляти',
    entscheiden: 'вирішувати',
    planen: 'планувати',
    organisieren: 'організовувати',
    erleben: 'досвідчувати',
    entdecken: 'відкривати',
    erforschen: 'досліджувати',
    unterstützen: 'підтримувати',
    verbessern: 'покращувати',
    trainieren: 'тренуватися',
    erholen: 'відпочивати',
    genießen: 'насолоджуватися',
    feiern: 'святкувати',
    lächeln: 'посміхатися',
    weinen: 'плакати',
    schreien: 'кричати'
  },
  adjectives: {
    groß: 'великий',
    klein: 'малий',
    lang: 'довгий',
    kurz: 'короткий',
    hoch: 'високий',
    niedrig: 'низький',
    alt: 'старий',
    jung: 'молодий',
    neu: 'новий',
    schön: 'гарний',
    hässlich: 'потворний',
    gut: 'добрий',
    schlecht: 'поганий',
    stark: 'сильний',
    schwach: 'слабкий',
    warm: 'теплий',
    kalt: 'холодний',
    heiß: 'гарячий',
    trocken: 'сухий',
    nass: 'мокрий',
    schnell: 'швидкий',
    langsam: 'повільний',
    leicht: 'легкий',
    schwer: 'важкий',
    teuer: 'дорогий',
    billig: 'дешевий',
    sauber: 'чистий',
    schmutzig: 'брудний',
    freundlich: 'дружній',
    unfreundlich: 'недружній',
    glücklich: 'щасливий',
    traurig: 'сумний',
    klug: 'розумний',
    dumm: 'дурний',
    lustig: 'смішний',
    ernst: 'серйозний',
    ruhig: 'спокійний',
    laut: 'голосний',
    interessant: 'цікавий',
    langweilig: 'нудний',
    gesund: 'здоровий',
    krank: 'хворий',
    reich: 'багатий',
    arm: 'бідний',
    sauber: 'чистий',
    scharf: 'гострий',
    weich: 'м’який',
    hart: 'твердий',
    schön: 'гарний',
    hässlich: 'потворний',
    offen: 'відкритий',
    geschlossen: 'закритий',
    bequem: 'зручний',
    unbequem: 'незручний',
    freundlich: 'дружній',
    feindlich: 'ворожий',
    sicher: 'безпечний',
    gefährlich: 'небезпечний',
    hell: 'світлий',
    dunkel: 'темний',
    warmherzig: 'добросердний',
    kaltblütig: 'бездушний',
    sauber: 'чистий',
    schmutzig: 'брудний',
    stolz: 'гордий',
    bescheiden: 'скромний',
    mutig: 'сміливий',
    ängstlich: 'боязкий',
    stark: 'сильний',
    schwach: 'слабкий',
    treu: 'вірний',
    untreu: 'невірний',
    freundlich: 'дружній',
    unfreundlich: 'недружній',
    elegant: 'елегантний',
    hässlich: 'потворний',
    warm: 'теплий',
    kalt: 'холодний',
    süß: 'солодкий',
    sauer: 'кислий',
    bitter: 'гіркий',
    salzig: 'солоний',
    dick: 'товстий',
    dünn: 'тонкий',
    sauber: 'чистий',
    schmutzig: 'брудний',
    scharf: 'гострий',
    stumpf: 'тупий',
    intelligent: 'розумний',
    dumm: 'дурний',
    lustig: 'веселий',
    traurig: 'сумний',
    glücklich: 'щасливий',
    unglücklich: 'нещасний',
    neu: 'новий',
    alt: 'старий',
    modern: 'сучасний',
    traditionell: 'традиційний',
    interessant: 'цікавий',
    langweilig: 'нудний',
    sauber: 'чистий',
    schmutzig: 'брудний',
    leicht: 'легкий',
    schwer: 'важкий',
    stark: 'сильний',
    schwach: 'слабкий',
    warm: 'теплий',
    kalt: 'холодний',
    nah: 'близький',
    fern: 'далекий',
    schön: 'гарний',
    hässlich: 'потворний',
    jung: 'молодий',
    alt: 'старий',
    offen: 'відкритий',
    verschlossen: 'замкнений'
  },
  nomen: {
    'der haus': 'будинок',
    'das auto': 'авто',
    'der stuhl': 'стілець',
    'der tisch': 'стіл',
    'das fenster': 'вікно',
    'die tür': 'двері',
    'das bett': 'ліжко',
    'die schule': 'школа',
    'der lehrer': 'вчитель',
    'die schülerin': 'учениця',
    'der schüler': 'учень',
    'die bücher': 'книги',
    'die stadt': 'місто',
    'das dorf': 'село',
    'die straße': 'вулиця',
    'der park': 'парк',
    'die brücke': 'міст',
    'der fluss': 'річка',
    'der see': 'озеро',
    'der berg': 'гора',
    'der wald': 'ліс',
    'die blume': 'квітка',
    'der baum': 'дерево',
    'der vogel': 'птах',
    'der hund': 'собака',
    'die katze': 'кішка',
    'der fisch': 'риба',
    'das essen': 'їжа',
    'das getränk': 'напій',
    'das brot': 'хліб',
    'die milch': 'молоко',
    'der kaffee': 'кава',
    'der tee': 'чай',
    'die suppe': 'суп',
    'der kuchen': 'тістечко',
    'die schokolade': 'шоколад',
    'der freund': 'друг',
    'die freundin': 'подруга',
    'die familie': 'сім’я',
    'die mutter': 'мати',
    'der vater': 'батько',
    'der bruder': 'брат',
    'die schwester': 'сестра',
    'die oma': 'бабуся',
    'der opa': 'дідусь',
    'das baby': 'дитина',
    'das kind': 'дитина',
    'der mann': 'чоловік',
    'die frau': 'жінка',
    'der junge': 'хлопчик',
    'das mädchen': 'дівчинка',
    'die arbeit': 'робота',
    'der chef': 'шеф',
    'der kollege': 'колега',
    'der termin': 'зустріч',
    'die stunde': 'година',
    'die minute': 'хвилина',
    'die sekunde': 'секунда',
    'der tag': 'день',
    'die woche': 'тиждень',
    'der monat': 'місяць',
    'das jahr': 'рік',
    'die saison': 'сезон',
    'der frühling': 'весна',
    'der sommer': 'літо',
    'der herbst': 'осінь',
    'der winter': 'зима',
    'das wetter': 'погода',
    'der regen': 'дощ',
    'der schnee': 'сніг',
    'der wind': 'вітер',
    'die sonne': 'сонце',
    'der mond': 'місяць',
    'der stern': 'зірка',
    'der himmel': 'небо',
    'das meer': 'море',
    'der strand': 'пляж',
    'der sand': 'пісок',
    'der stein': 'камінь',
    'das blatt': 'листок',
    'das gras': 'трава',
    'das tier': 'тварина',
    'der zoo': 'зоопарк',
    'das krankenhaus': 'лікарня',
    'der arzt': 'лікар',
    'die apotheke': 'аптека',
    'der supermarkt': 'супермаркет',
    'der laden': 'магазин',
    'der markt': 'ринок',
    'der bahnhof': 'вокзал',
    'der zug': 'поїзд',
    'der bus': 'автобус',
    'das flugzeug': 'літак',
    'das fahrrad': 'велосипед',
    'die straßenbahn': 'трамвай',
    'das taxi': 'таксі',
    'der flughafen': 'аеропорт',
    'der koffer': 'чемодан',
    'die tasche': 'сумка',
    'das telefon': 'телефон',
    'der computer': 'комп’ютер',
    'das handy': 'мобільний телефон',
    'das buch': 'книга',
    'die zeitung': 'газета',
    'das foto': 'фото',
    'der film': 'фільм',
    'die musik': 'музика',
    'das spiel': 'гра',
    'das hobby': 'хобі',
    'der sport': 'спорт',
    'das team': 'команда',
    'die liga': 'ліга',
    'der spieler': 'гравець',
    'der trainer': 'тренер'
  },
  natur: {
    'der baum': 'дерево',
    'die blume': 'квітка',
    'das gras': 'трава',
    'der wald': 'ліс',
    'der berg': 'гора',
    'der fluss': 'річка',
    'der see': 'озеро',
    'das meer': 'море',
    'die küste': 'берег',
    'der strand': 'пляж',
    'der sand': 'пісок',
    'der stein': 'камінь',
    'der himmel': 'небо',
    'die wolke': 'хмара',
    'die sonne': 'сонце',
    'der mond': 'місяць',
    'der stern': 'зірка',
    'der regen': 'дощ',
    'der schnee': 'сніг',
    'der wind': 'вітер',
    'das wetter': 'погода',
    'der nebel': 'туман',
    'der hagel': 'град',
    'der blitz': 'блискавка',
    'der donner': 'грім',
    'der sturm': 'шторм',
    'der orkan': 'ураган',
    'die hitze': 'спека',
    'die kälte': 'холод',
    'der frost': 'мороз',
    'die temperatur': 'температура',
    'die jahreszeit': 'пора року',
    'der frühling': 'весна',
    'der sommer': 'літо',
    'der herbst': 'осінь',
    'der winter': 'зима',
    'der regenbogen': 'веселка',
    'die blätter': 'листи',
    'der ast': 'гілка',
    'der stamm': 'стовбур',
    'die wiese': 'луг',
    'das tal': 'долина',
    'der hügel': 'пагорб',
    'die höhle': 'печера',
    'der vulkan': 'вулкан',
    'der geysir': 'гейзер',
    'die quelle': 'джерело',
    'der wasserfall': 'водоспад',
    'die ebene': 'рівнина',
    'der sumpf': 'болото',
    'das moor': 'торфовище',
    'die insel': 'острів',
    'die halbinsel': 'півострів',
    'die küstenlinie': 'берегова лінія',
    'der ozean': 'океан',
    'die tide': 'приплив',
    'die strömung': 'потік',
    'der regenwald': 'тропічний ліс',
    'die steppe': 'степ',
    'die wüste': 'пустеля',
    'die landschaft': 'ландшафт',
    'der naturpark': 'природний парк',
    'der nationalpark': 'національний парк',
    'der gletscher': 'льодовик',
    'der eisberg': 'айсберг',
    'der neuschnee': 'свіжий сніг',
    'der schneesturm': 'снігова буря',
    'die eisfläche': 'льодова поверхня',
    'der tornado': 'торнадо',
    'der taifun': 'тайфун',
    'der niederschlag': 'опади',
    'die bewölkung': 'покриття хмарами',
    'die trockenheit': 'посуха',
    'die flut': 'повінь',
    'die überschwemmung': 'затоплення',
    'der sandsturm': 'пилова буря',
    'der dunst': 'димка',
    'die brise': 'легкий вітерець',
    'der orkanböe': 'ураганний порив вітру',
    'die klimazone': 'кліматична зона',
    'das klima': 'клімат',
    'der temperatursprung': 'стрибок температури',
    'die hitzewelle': 'хвиля спеки',
    'die kälteeinbruch': 'різке похолодання',
    'die feuchtigkeit': 'вологість',
    'die trockenheit': 'сухість',
    'der regenfall': 'зливові опади',
    'der schneefall': 'снігопад',
    'die lawine': 'лавина',
    'der erdrutsch': 'землетрус',
    'der vulkanausbruch': 'виверження вулкана',
    'die erde': 'земля',
    'die natur': 'природа',
    'das ökosystem': 'екосистема',
    'die biodiversität': 'біорізноманіття',
    'die pflanze': 'рослина',
    'das tier': 'тварина',
    'die jagd': 'мисливство',
    'die fischerei': 'рибальство',
    'die landschaftspflege': 'догляд за ландшафтом',
    'der naturfreund': 'любитель природи',
    'der naturschutz': 'охорона природи',
    'die erneuerbare energie': 'відновлювана енергія',
    'das fossil': 'фосилія',
    'der garten': 'сад',
    'der park': 'парк',
    'der bach': 'струмок',
    'die aue': 'луг при річці',
    'die schlucht': 'ущелина',
    'das rifff': 'риф',
    'die felswand': 'скеляста стіна',
    'die klippe': 'круча'
  },
  autofahren: {
    'das auto': 'автомобіль',
    'der wagen': 'автомобіль',
    'der fahrer': 'водій',
    'die fahrerin': 'водійка',
    'das lenkrad': 'кермо',
    'die bremse': 'гальмо',
    'die kupplung': 'зчеплення',
    'das gaspedal': 'педаль газу',
    'der tachometer': 'швидкісометр',
    'der kilometerzähler': 'одометр',
    'die geschwindigkeit': 'швидкість',
    'die spur': 'смуга',
    'die autobahn': 'автобан',
    'die straße': 'вулиця',
    'der parkplatz': 'парковка',
    'die ampel': 'світлофор',
    'das schild': 'дорожній знак',
    'die kurve': 'поворот',
    'die abfahrt': 'з’їзд',
    'die auffahrt': 'виїзд на трасу',
    'das tanken': 'заправка',
    'die tankstelle': 'заправна станція',
    'der kraftstoff': 'паливо',
    'der diesel': 'дизель',
    'das benzín': 'бензин',
    'das elektroauto': 'електромобіль',
    'der hybrid': 'гібрид',
    'die batterie': 'акумулятор',
    'der motor': 'двигун',
    'das getriebe': 'коробка передач',
    'der kofferraum': 'багажник',
    'die tür': 'двері',
    'die scheibe': 'вікно',
    'die spiegel': 'дзеркало',
    'die scheibenwischer': 'склоочисники',
    'das licht': 'світло',
    'der scheinwerfer': 'фара',
    'das bremslicht': 'стоп-сигнал',
    'die blinker': 'поворотник',
    'das heck': 'задня частина',
    'die stoßstange': 'бампер',
    'der reifen': 'шина',
    'das rad': 'колесо',
    'die felge': 'диск',
    'die luft': 'повітря',
    'der luftdruck': 'тиск повітря',
    'der wagenheber': 'домкрат',
    'das ersatzrad': 'запасне колесо',
    'die werkstatt': 'майстерня',
    'das öl': 'олія',
    'der ölwechsel': 'заміна олії',
    'der service': 'сервіс',
    'die garantie': 'гарантія',
    'die zulassung': 'реєстрація',
    'das kennzeichen': 'номерний знак',
    'die polizei': 'поліція',
    'das bußgeld': 'штраф',
    'die geschwindigkeitsbegrenzung': 'обмеження швидкості',
    'die maut': 'плата за проїзд',
    'die versicherung': 'страхування',
    'die pannenhilfe': 'допомога при поломці',
    'die autobahnpolizei': 'поліція автобану',
    'der unfall': 'аварія',
    'die rettung': 'швидка допомога',
    'die karosserie': 'кузов',
    'der sitz': 'сидіння',
    'der sicherheitsgurt': 'пас безпеки',
    'das airbag': 'подушка безпеки',
    'das lenksystem': 'кермове управління',
    'die fahrbahn': 'проїжджа частина',
    'die ampelphase': 'фаза світлофора',
    'die überholspur': 'полоса для обгону',
    'die unterführung': 'підземний перехід',
    'die brücke': 'міст',
    'der tunnel': 'тунель',
    'die ausfahrt': 'виїзд',
    'die einfahrt': 'в’їзд',
    'der kreisel': 'круговий рух',
    'der stoppschild': 'стоп',
    'die parkzone': 'зона паркування',
    'der parkautomat': 'паркомат',
    'die gebühr': 'плата',
    'die tankanzeige': 'індикатор палива',
    'der kühlmittel': 'охолоджуюча рідина',
    'die scheibenwischflüssigkeit': 'рідина для склоочисника',
    'die autobahnraststätte': 'зона відпочинку на автобані',
    'der verkehr': 'трафік',
    'die verkehrsregeln': 'правила дорожнього руху',
    'der stau': 'затор',
    'die umleitung': 'об’їзд',
    'der lkw': 'вантажівка',
    'der bus': 'автобус',
    'das motorrad': 'мотоцикл',
    'das fahrrad': 'велосипед',
    'die fahrt': 'поїздка',
    'der ausflug': 'екскурсія',
    'die reise': 'подорож',
    'der anhalter': 'попутник',
    'die pannenwarnleuchte': 'індикатор поломки',
    'der abschleppwagen': 'евакуатор',
    'das navigationssystem': 'GPS-навігація',
    'der kartenplotter': 'картографічний навігатор'
  },
  ausgewählt: {

  },
}

export {arrContent, }


